### ISSUE TITLE
ILRuntime对vs版本以及.net有做要求么？

### ISSUE THREAD

**Issue by blueberryWT** [liiir1985/ILRuntime#1]
想问一下，这套方案对vs版本和.net版本是否有做要求，会不会不同的vs/net版本不同导致生成IL代码略有不同，以至于解析出错？

**Comment by liiir1985** [comment]
对vs和.net的版本并没有要求，不同版本的.net编译出来dll并没有太大差别，只是新的.net编译器优化的好些，生成的il指令会相对更少一点而已，真正区别在于系统库
我现在测试的是Unity的mono2.6和VS2015，VS2013，其他版本的.net没有测试过，理论上是没问题的，实际上得看具体情况了

**Comment by blueberryWT** [comment]
大神建一个QQ群方便大家一起学习一下这套热更新方案呗，我很多朋友都非常感兴趣！

**Comment by liiir1985** [comment]
有QQ群啊：512079820
