### ISSUE TITLE
Delegate Null CallBack

### ISSUE THREAD

**Issue by goodcxm** [liiir1985/ILRuntime#11]
///Unity Class 
public class ResourceBase
    {

    }
    public abstract class AssetBundleLoader
    {

    }

    public class AssetBundleLoader<T> : AssetBundleLoader
    {
        public Action<T> OnLoadOver;

        public void LoadOver(T o)
        {
            if (OnLoadOver != null)
            {
                OnLoadOver(o);
            }
        }
    }

///Dll Test
 public static void TestDelegateNull()
        {
            Console.WriteLine("TestDelegateNull ");
            AssetBundleLoader<ResourceBase> gg=new AssetBundleLoader<ResourceBase>();
            gg.OnLoadOver = OnLoadOver;
            gg.LoadOver(null);
            Console.WriteLine("TestDelegateNull end ");
        }

        public static void OnLoadOver(ResourceBase rb)
        {
            Console.WriteLine("OnLoadOver");
        }

**Comment by liiir1985** [comment]
用例运行没有任何问题
