### ISSUE TITLE
out issue

### ISSUE THREAD

**Issue by shmilypyj** [liiir1985/ILRuntime#16]
static bool TryGet(out A a)
		{
			a = null;
			return true;
		}

		public static string Test()
		{
			A aaa;
			TryGet(out aaa);
               }

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[System.Object].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRT/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:807)
Rethrow as ILRuntimeException: Argument is out of range.
Parameter name: index
IL_0002: stind.ref
Game.DSimpleTown.TryInSoldierLst(Int32 soldierId, DSoldier& dSoldier) Code/Data/Player/DSimpleTown.cs:Line 75

**Comment by liiir1985** [comment]
This issue should be fixed
