### ISSUE TITLE
T issue

### ISSUE THREAD

**Issue by shmilypyj** [liiir1985/ILRuntime#17]
public static void Swap<T>(T[] arr, int idx1, int idx2)
		{
			if (idx1 >= arr.Length || idx2 >= arr.Length) return;
			T temp = arr[idx1];
			arr[idx1] = arr[idx2];
			arr[idx2] = temp;
		}

		public static string Test()
		{
			Swap(new int[] { 1, 2 }, 0, 1);
}

NotImplementedException: The requested feature is not implemented.
ILRuntime.CLR.TypeSystem.ILGenericParameterType.MakeArrayType () (at Assets/ILRT/ILRuntime/CLR/TypeSystem/ILGenericParameterType.cs:113)
ILRuntime.CLR.Method.ILMethod.InitParameters () (at Assets/ILRT/ILRuntime/CLR/Method/ILMethod.cs:500)
ILRuntime.CLR.Method.ILMethod.get_Parameters () (at Assets/ILRT/ILRuntime/CLR/Method/ILMethod.cs:198)

**Comment by liiir1985** [comment]
It's now fixed
