### ISSUE TITLE
string format throw exception

### ISSUE THREAD

**Issue by ifshuaishuai** [liiir1985/ILRuntime#3]
hi:
   i write following code in the dll:
```
float a = 1.0f;
float b = a/2;
var str = string.Format("{0:0.000}", b);
```
run with exception:

> NotImplementedException: The requested feature is not implemented.
> ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:2135)
> Rethrow as ILRuntimeException: The requested feature is not implemented.
> IL_0012: box System.Single
> HotFix_Project.InstanceClass.TestError() I:/New_Project/unity_lua_benchmark/HotFix-Project/InstanceClass.cs:Line 39

but following code works fine:
```
float a = 1.0f;
var str = string.Format("{0:0.000}", a);
```

it's maybe a boxing issue?

**Comment by liiir1985** [comment]
It's not a boxing issue, it's a bug with div instruction, which returns a long with a / 2, can it cannot be boxed into float.
It's fixed and committed.
