### ISSUE TITLE
Dll里面对象实现继承后，在c#层调用GetFeilds()会报错

### ISSUE THREAD

**Issue by blueberryWT** [liiir1985/ILRuntime#4]

**Comment by blueberryWT** [comment]
dll
定义部分：
`    public class DMTestModel: BaseModel
    {
        public string MyName;

        public int age;

        public void Test01()
        {
        }

        public void Test02()
        {
            age++;
        }


        public static void Test03()
        {
            
        }
    }


    public class BaseModel
    {
        public string baseName = "base name";
    }`

c#
调用部分：
`    public static string MyTestSeriable(object _testModel)
    {
        Type refType = ((ILTypeInstance)_testModel).Type.ReflectionType;
        
       // 下面这句会报异常
        FieldInfo[] info = refType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

        
        return "";
    }`

异常信息：
`IndexOutOfRangeException: Array index is out of range.
ILRuntime.Reflection.ILRuntimeFieldInfo..ctor (Mono.Cecil.FieldDefinition def, ILRuntime.Reflection.ILRuntimeType declaredType, Boolean isStatic, Int32 fieldIdx) (at Assets/IL/ILRuntime/Reflection/ILRuntimeFieldInfo.cs:46)
ILRuntime.Reflection.ILRuntimeType.InitializeFields () (at Assets/IL/ILRuntime/Reflection/ILRuntimeType.cs:59)
ILRuntime.Reflection.ILRuntimeType.GetFields (BindingFlags bindingAttr) (at Assets/IL/ILRuntime/Reflection/ILRuntimeType.cs:192)
HKMainAppdelegate.MyTestSeriable (System.Object _testModel) (at Assets/HKScripts/HKMainAppdelegate.cs:102)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
ILRuntime.CLR.Method.CLRMethod.Invoke (ILRuntime.Runtime.Intepreter.ILIntepreter intepreter, ILRuntime.Runtime.Stack.StackObject* esp, System.Collections.Generic.List`1 mStack, Boolean isNewObj) (at Assets/IL/ILRuntime/CLR/Method/CLRMethod.cs:254)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/IL/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1465)
Rethrow as ILRuntimeException: Exception has been thrown by the target of an invocation.
IL_0071: call System.String HKMainAppdelegate::MyTestSeriable(System.Object)
DMILRT.ILRTController.ILRTLoginController.Test() E:/BuildingDream/Dreamer/DMILRT/ILRTController/ILRTLoginController.cs:Line 45
DMILRT.ILRTMain.ILRTMain.Main() E:/BuildingDream/Dreamer/DMILRT/ILRTMain/ILRTMain.cs:Line 25`

**Comment by liiir1985** [comment]
应该修复了
求验证
