### ISSUE TITLE
脚本继承c#类，导致的脚本中的方法多执行一次

### ISSUE THREAD

**Issue by blueberryWT** [liiir1985/ILRuntime#7]
如果我 ILRTClass继承了 c#Class，并且在test()函数里执行力base.xxx() 那么，我在c#里通过 app.invoke(instance, "test")来调用这个方法的时候,  test里面的代码就会执行两次。因为一次是我invoke调用的，一次貌似是adapter中转的时候调用的

c#
//#if ILRT
    [ILRuntime.Other.NeedAdaptor]
//#endif

    public class HKSpriteModel
    {
        public string ModelName;

        public virtual void InitModel()
        {
            this.LogMessageInfo("parent init");
        }
    }

ILRT
public class HKMonsterSpriteModel : HKSpriteModel
    {
        public int index = 0;
        public override void InitModel()
        {
            base.InitModel();
            Debug.Log("sub init");
            index++;
        }

        public void test()
        {
            InitModel();
            this.LogMessageInfo("index = " + index + this.ModelName);
        }

    }

c#中调用部分
app.invoke(instance, "InitModel", null)   

结果：
会输出两次 "sub init"
并且 index = 2 了

**Comment by liiir1985** [comment]
如果instance是CLR类型的子类，则应该直接调用CLR基类上的方法，而不是通过app.Invoke来调用，否则很难处理这个问题
