### ISSUE TITLE
T issue

### ISSUE THREAD

**Issue by shmilypyj** [liiir1985/ILRuntime#8]
`public class B
	{
		public int aa = 2;
		public virtual void Print()
		{
			Debug.Log("I am B"); ;
		}
	}

	public class Class1
	{
		public static void ParseDB<T>(System.Action<T> cbk) where T : B, new()
		{
			
		}
		public static string Test()
		{
			ParseDB<B>((d) =>
			{

			});

			return "xxxx1";
		}
}`

**Comment by liiir1985** [comment]
It should be fixed
